import "../styles/globals.css";
import NavBar from "@/components/NavBar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-300 border-slate-500">
        <NavBar></NavBar>

        {children}
      </body>
    </html>
  );
}
